[workspace]
members = [ "pwm-cli", "pwm-db", "pwm-lib", "pwm-proc"]
resolver = "2"


# [package]
# name = "pwm"
# version = "0.1.0"
# edition = "2021"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]

