[package]
name = "pwm-db"
version = "0.2.0"
edition = "2021"

[features]

[dependencies]
pwm-lib = { path = "../pwm-lib" }
serde = { version = "1.0.198", features = ["derive"] }
bincode = "1.3.3" 
csv = "1.3.0"
fuzzy-matcher = "0.3.7"
