[package]
name = "pwm-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwm-lib = { path = "../pwm-lib" }
clap = { version = "4.5.4", features = ["derive"] }
rpassword = "7.3.1"