[package]
name = "pwm-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwm-db = {path = "../pwm-db"}
pwm-lib = {path = "../pwm-lib"}
iced = "0.12.1"
