[package]
name = "pwm-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = "0.5.2"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
pbkdf2 = "0.12.2"
scrypt = { vesion = "0.11.0", default-features = false }
sha2 = "0.10.8"
zeroize = "1.7.0"